<template>
  <div
    v-show="show"
    :class="computedWrapperCssClass"
    :style="computedWrapperCssStyle"
  >
    <slot>
      <form-validation
        :label="label"
        :id="identity"
        :name="name"
        :show="showValidation"
        :css-class="computedValidationCssClass"
        :validation="computedValidation"
        :error="error"
      ></form-validation>
    </slot>
    <input
      :type="type"
      :id="identity"
      :name="name"
      :value="value"
      :maxlength="maxlength"
      :placeholder="placeholder"
      :autocomplete="autocomplete"
      :class="inputCssClass"
      v-focus="focus"
      v-on="inputListeners"
      :disabled="isDisabled"
      v-bind="attributeBindings"
    />
  </div>
</template>
